name: 部署 (预览环境)

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: 检查文档格式
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      fix: true
    secrets: inherit

  build:
    name: 构建文档
    uses: ./.github/workflows/build.yml

  upload:
    name: 上传运行信息
    runs-on: ubuntu-latest
    if: github.repository == 'zotero-chinese/wiki' && github.event_name == 'pull_request'
    steps:
      - name: 保存 PR 编号
        run: |
          echo "${{ github.event.number }}" > pr_num
      - name: 上传 PR 编号
        uses: actions/upload-artifact@v4
        with:
          name: pr-num
          path: ./pr_num
