name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: 检查文档格式
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      fix: ${{ github.event_name == 'pull_request' }}

  build:
    name: 构建文档
    uses: ./.github/workflows/build.yml

  upload:
    name: 上传运行信息
    runs-on: ubuntu-latest
    if: github.repository == 'zotero-chinese/wiki' && github.event_name == 'pull_request'
    steps:
      - name: 保存 PR 编号
        run: |
          echo "${{ github.event.number }}" > pr_num
      - name: 上传 PR 编号
        uses: actions/upload-artifact@v2
        with:
          name: pr-num
          path: ./pr_num

  send-dispatch:
    name: 请求部署上线
    if: github.repository == 'zotero-chinese/wiki' && github.event_name != 'pull_request'
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: zotero-chinese/website
          event-type: update-content
