name: Deploy GitHub Pages

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4

      - name: 下载构建内容
        uses: actions/download-artifact@v4
        with:
          name: build-result
          # path: dist.tar

      - name: 解压构建文件
        run: tar -xvf dist.tar src/.vuepress/dist

      - name: 列出构建内容目录结构
        run: ls -R -a

      - name: 部署到 GitHub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: zotero-chinese/zotero-chinese.github.io
          branch: gh-pages
          folder: src/.vuepress/dist
          single-commit: true
          token: ${{ secrets.ACCESS_TOKEN }}
