name: Deploy GitHub Pages

on:
  workflow_call:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Build Result
        uses: actions/download-artifact@v3
        with:
          name: build-result
          path: ./src/.vuepress/dist

      - name: Display structure of downloaded files
        run: ls -R -a

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          repository-name: zotero-chinese/zotero-chinese.github.io
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
