name: Lint Markdown

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4
      - name: 运行 MarkdownLint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
            !test/*.md
