name: Lint Markdown

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: lint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: |
            **/*.md
            !test/*.md
    outputs:
      lintLog: ${{ steps.lint.outputs.firstword }}
